name: Spring Boot CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # 깃허브가 빌려주는 가상의 리눅스 컴퓨터

    steps:
      - name: Checkout 코드를 가져옵니다
        uses: actions/checkout@v3

      - name: JDK 17을 설치합니다
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto' # 실무에서 많이 쓰는 AWS 자바 버전

      - name: gradlew 실행 권한을 부여합니다
        run: chmod +x gradlew

      - name: Spring Boot 프로젝트를 빌드합니다 (테스트 제외)
        # 지금 깃허브 컴퓨터엔 우리 로컬 DB(도커)가 없어서 테스트는 빼고 순수하게 코드 에러만 검사!
        run: ./gradlew build -x test